apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adapt-front
  name: adapt-front
spec:
  replicas: {{ .Values.replica.count }}
  selector:
    matchLabels:
      app: adapt-front
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adapt-front
    spec:
      containers:
      - image: {{ .Values.image.name }}
        name: bfctech
        resources: {}
status: {}
